export const airlines = [
  ['0B', 'BBN Airlines Indonesia'],
  ['0C', 'Cobra Aviation'],
  ['0J', 'Premium Jet'],
  ['0V', 'SalamAir'],
  ['1C', 'A-ICE'],
  ['1J', 'Navios Evolusia Solusindo'],
  ['1L', 'CitizenPlane'],
  ['1N', 'Navitaire'],
  ['2A', 'Air Astra'],
  ['2D', 'Eastern Airlines'],
  ['2F', 'Azul Conecta'],
  ['2G', 'Hungary Airlines'],
  ['2H', 'THI Factory'],
  ['2J', 'Air Burkina'],
  ['2K', 'Avianca Ecuador'],
  ['2L', 'Helvetic Airways'],
  ['2M', 'Maya Island Air'],
  ['2N', 'SmartLynx Airlines Malta'],
  ['2O', 'Redemption Inc.'],
  ['2P', 'PAL Express'],
  ['2R', 'Sunlight Air'],
  ['2S', 'Southwind Airlines'],
  ['2U', 'Fly Khiva'],
  ['2V', 'Amtrak'],
  ['2W', 'W2FLY'],
  ['2Y', 'My Indo Airlines'],
  ['3C', 'Air Chathams'],
  ['3F', 'FLYONE Armenia'],
  ['3K', 'Jetstar Asia Airways'],
  ['3L', 'Air Arabia'],
  ['3M', 'Silver Airways'],
  ['3N', 'Air Urga'],
  ['3O', 'Air Arabia Maroc'],
  ['3P', 'World2Fly Portugal'],
  ['3R', 'Divi Divi Air'],
  ['3S', 'Aerologic'],
  ['3S', 'AeroLogic'],
  ['3T', 'Tarco Aviation'],
  ['3U', 'Sichuan Airlines'],
  ['3V', 'Airlines Belgium'],
  ['3W', 'Malawi Airlines'],
  ['3X', 'Premier Trans Aire'],
  ['3Z', 'Smartwings Poland'],
  ['4A', 'ATSA Airline'],
  ['4B', 'Boutique Air'],
  ['4C', 'LATAM Airlines Colombia'],
  ['4D', 'FLYYO'],
  ['4E', 'Stabo Air'],
  ['4F', 'Freedom Airline Express'],
  ['4G', 'Gazpromavia'],
  ['4H', 'Trans Pacific Air'],
  ['4I', 'Air Antilles'],
  ['4K', 'Freedom Airline Express'],
  ['4M', 'MGA'],
  ['4N', "Air North Yukon's Airline"],
  ['4O', 'Air Montenegro'],
  ['4S', 'Red Sea Airlines'],
  ['4T', 'Transwest Air'],
  ['4U', 'XE Jet'],
  ['4Z', 'Airlink'],
  ['5A', 'LaneXang'],
  ['5C', 'Challenge Airlines IL'],
  ['5D', 'Aeroméxico Connect'],
  ['5F', 'FlyOne'],
  ['5G', 'Shirak Avia'],
  ['5J', 'Cebu Pacific Air'],
  ['5K', 'HiFly'],
  ['5L', 'LIAT 20'],
  ['5M', 'FlyMontserrat'],
  ['5N', 'Smartavia Airlines'],
  ['5O', 'ASL Airlines France'],
  ['5P', 'Panorama Airways'],
  ['5R', 'Rutaca Airlines'],
  ['5S', 'Global Air Transport'],
  ['5V', 'Everts Air'],
  ['5W', 'Wizz Air'],
  ['5Y', 'Atlas Air'],
  ['5Z', 'CemAir'],
  ['6A', 'Armenia Airways'],
  ['6B', 'TUIfly Nordic'],
  ['6D', 'Smartwings Slovakia'],
  ['6E', 'IndiGo'],
  ['6G', 'Air Vegas'],
  ['6H', 'Israir'],
  ['6J', 'Solaseed Air'],
  ['6K', 'Air Anka'],
  ['6N', 'Niger Airlines'],
  ['6P', 'Pradhaan Air Express'],
  ['6R', 'AeroUnion'],
  ['6Y', 'Smartlynx Airlines'],
  ['7B', 'Bees Airline'],
  ['7C', 'Coyne Airways'],
  ['7E', 'Sylt Air'],
  ['7F', 'Fanjet Express'],
  ['7G', 'Star Flyer'],
  ['7H', 'New Pacific Airlines'],
  ['7K', 'AmSafe Bridport'],
  ['7L', 'Silk Way West Airlines'],
  ['7M', 'Map Linhas Aereas'],
  ['7N', 'MetroJets'],
  ['7O', 'Smartwings Hungary'],
  ['7R', 'RusLine '],
  ['7S', 'Ryan Air'],
  ['7T', 'Aero Express del Ecuador'],
  ['7W', 'WINDROSE Airlines'],
  ['8A', 'Panama Airways'],
  ['8B', 'TransNusa'],
  ['8C', 'Air Transport International'],
  ['8D', 'Fits Air'],
  ['8E', 'Bering Air'],
  ['8F', 'STP Airways'],
  ['8H', 'BH Air'],
  ['8I', 'Lipican Aer'],
  ['8J', 'EcoJet'],
  ['8K', 'K-Mile Air'],
  ['8L', 'Lucky Air'],
  ['8M', 'Myanmar Airways International'],
  ['8N', 'Regional Air Services'],
  ['8O', 'West Coast Air'],
  ['8P', 'Pacific Coastal Airlines'],
  ['8S', 'TurboJet'],
  ['8T', 'Air Tindi'],
  ['8U', 'Afriqiyah Airways'],
  ['8V', 'Wright Air Service'],
  ['8W', 'Fly AllWays'],
  ['9C', 'Spring Airlines'],
  ['9D', 'Genghis Khan Airlines'],
  ['9E', 'Endeavor Air'],
  ['9I', 'Alliance Air'],
  ['9K', 'Cape Air'],
  ['9L', 'Linkasia'],
  ['9M', 'Central Mountain Air'],
  ['9P', 'Fly Jinnah'],
  ['9Q', 'Caicos Express'],
  ['9R', 'SATENA'],
  ['9T', 'Air ACT'],
  ['9U', 'Air Moldova'],
  ['9V', 'Avior Airlines'],
  ['9X', 'Southern Airways Express'],
  ['9Y', 'National Airways Ethiopia'],
  ['A0', 'BA EuroFlyer'],
  ['A2', 'Animawings'],
  ['A3', 'Aegean Airlines'],
  ['A4', 'Azimuth Airlines'],
  ['A5', 'HOP!'],
  ['A6', 'Air Travel'],
  ['A8', 'Aerolink'],
  ['A9', 'Georgian Airways'],
  ['AA', 'American Airlines'],
  ['AB', 'Sun Air Bulgaria'],
  ['AC', 'Air Canada'],
  ['AD', 'Azul'],
  ['AE', 'Mandarin Airlines'],
  ['AF', 'Air France'],
  ['AG', 'Aruba Airlines'],
  ['AH', 'Air Algerie'],
  ['AI', 'Air India'],
  ['AJ', 'Aztec Airways'],
  ['AK', 'Air Asia'],
  ['AL', 'Alpavia'],
  ['AM', 'Aeromexico'],
  ['AN', 'Advanced Air'],
  ['AP', 'Alba Star'],
  ['AQ', '9 Air '],
  ['AR', 'Aerolineas Argentinas'],
  ['AS', 'Alaska Airlines'],
  ['AT', 'Royal Air Maroc'],
  ['AU', 'Austral'],
  ['AV', 'Avianca'],
  ['AW', 'Africa World Airlines'],
  ['AY', 'Finnair'],
  ['AZ', 'ITA Airways'],
  ['B2', 'Belavia'],
  ['B3', 'Bhutan Airlines'],
  ['B4', 'Beond'],
  ['B5', 'BBN Airlines'],
  ['B6', 'Jetblue Airways'],
  ['B7', 'UNI Airways'],
  ['B8', 'Eritrean Airlines'],
  ['B9', 'Iran Airtour'],
  ['BA', 'British Airways'],
  ['BB', 'Seaborne Airlines'],
  ['BC', 'Skymark Airlines'],
  ['BD', 'British Midland Airways'],
  ['BE', 'Brightline Trains Florida'],
  ['BF', 'French bee'],
  ['BG', 'Biman Bangladesh Airlines'],
  ['BH', 'BH Air'],
  ['BI', 'Royal Brunei Airlines'],
  ['BJ', 'Nouvel Air Tunisie'],
  ['BK', 'Okay Airways'],
  ['BL', 'Pacific Airlines'],
  ['BM', 'Medsky Airways'],
  ['BN', 'Luxwing'],
  ['BP', 'Air Botswana'],
  ['BQ', 'Sky Alps'],
  ['BR', 'EVA Airways'],
  ['BS', 'US-Bangla Airlines'],
  ['BT', 'Air Baltic'],
  ['BU', "Compagnie Africaine d'Aviation"],
  ['BV', 'TOKi Air'],
  ['BW', 'Caribbean Airlines'],
  ['BX', 'Air Busan'],
  ['BY', 'TUI'],
  ['BZ', 'Blue Dart Aviation'],
  ['C5', 'CommuteAir'],
  ['C6', 'My Freighter'],
  ['C7', 'Cinnamon Air'],
  ['C8', 'Cronos Airlines'],
  ['CA', 'Air China'],
  ['CC', 'Air Atlanta Icelandic'],
  ['CD', 'Corendon Dutch Airlines'],
  ['CE', 'Chalair Aviation'],
  ['CG', 'PNG Air'],
  ['CH', 'Bemidji Aviation Services, Inc.'],
  ['CI', 'China Airlines'],
  ['CJ', 'BA Cityflyer'],
  ['CL', 'Lufthansa CityLine'],
  ['CM', 'Copa Airlines'],
  ['CN', 'Grand China Air'],
  ['CP', 'MSC Air'],
  ['CQ', 'Coastal Air'],
  ['CS', 'Chair Airlines'],
  ['CT', 'Air Atlanta Europe'],
  ['CU', 'Cubana'],
  ['CW', 'SkyWest Charter'],
  ['CX', 'Cathay Pacific Airways'],
  ['CY', 'Cyprus Airways'],
  ['CZ', 'China Southern Airlines'],
  ['D0', 'DHL Air'],
  ['D2', 'Severstal'],
  ['D3', 'Daallo Airlines'],
  ['D4', 'Geo Sky'],
  ['D5', 'DHL Aero Expreso'],
  ['D6', 'Sunrise Airways Dominicana'],
  ['D7', 'AirAsia X'],
  ['D8', 'Norwegian Air Sweden '],
  ['D9', 'Daallo Airlines Somalia'],
  ['DB', 'Maleth-Aero'],
  ['DC', 'Aeronaves Dominicanas'],
  ['DD', 'Nok Air'],
  ['DE', 'Condor'],
  ['DH', 'FlyAden'],
  ['DI', 'Marabu'],
  ['DJ', 'Air Djibouti'],
  ['DK', 'SunClass Airlines'],
  ['DL', 'Delta Airlines'],
  ['DM', 'Arajet'],
  ['DN', 'Dan Air'],
  ['DO', 'Sky High Dominicana'],
  ['DP', 'Pobeda'],
  ['DQ', 'Alexandria Airlines'],
  ['DS', 'Easyjet Switzerland'],
  ['DT', 'TAAG Angola Airlines'],
  ['DU', 'Sky Jet M.G.'],
  ['DV', 'Scat Air'],
  ['DX', 'DAT'],
  ['DY', 'Norwegian Air Shutlle'],
  ['DZ', 'Donghai Airlines'],
  ['E0', 'Eos Airlines'],
  ['E2', 'airHaifa'],
  ['E3', 'East Asia Airlines '],
  ['E4', 'Abaete Aerotaxi'],
  ['E5', 'Air Arabia Egypt'],
  ['E6', 'Eurowings Europe'],
  ['E9', 'Iberojet Airlines'],
  ['EA', 'Atlantis-Air Link'],
  ['EC', 'easyJet Europe'],
  ['ED', 'AirExplore'],
  ['EG', 'Aer Lingus UK'],
  ['EH', 'ANA Wings'],
  ['EI', 'Aer Lingus'],
  ['EJ', 'Equatorial Congo Airlines'],
  ['EK', 'Emirates'],
  ['EL', 'Ellinair'],
  ['EM', 'Empire Airlines'],
  ['EN', 'Air Dolomiti'],
  ['EO', 'Pegas Fly'],
  ['EP', 'Iran Aseman Airline'],
  ['EQ', 'TEA (UK)'],
  ['ER', 'Serene Air'],
  ['ES', 'Estelar'],
  ['ET', 'Ethiopian Airlines'],
  ['EU', 'Chengdu Airlines'],
  ['EW', 'Eurowings'],
  ['EX', 'Avianca Express'],
  ['EY', 'Etihad'],
  ['EZ', 'Sun Air of Scandinavia'],
  ['F2', 'Safarilink Aviation'],
  ['F3', 'Flyadeal'],
  ['F4', 'FLY 4'],
  ['F6', 'Fly2Sky'],
  ['F7', 'iFly Airlines'],
  ['F8', 'Flair Airlines'],
  ['F9', 'Frontier Airlines'],
  ['FA', 'Fly Safair'],
  ['FB', 'Bulgaria Air'],
  ['FC', 'LINK Airways'],
  ['FD', 'Thai AirAsia'],
  ['FE', '748 Air Services'],
  ['FG', 'Ariana Afghan Airlines'],
  ['FH', 'Freebird Airlines'],
  ['FI', 'Icelandair'],
  ['FJ', 'Fiji Airways'],
  ['FK', 'Kelowna Flightcraft Air'],
  ['FL', 'Fly Lili'],
  ['FM', 'Shanghai Airlines'],
  ['FN', 'fastjet Zimbabwe'],
  ['FO', 'Flybondi'],
  ['FP', 'Flypelican'],
  ['FR', 'Ryanair'],
  ['FS', 'Airfast Indonesia'],
  ['FT', 'Flying Tiger'],
  ['FV', 'Rossiya Airlines'],
  ['FW', 'Ibex Airlines'],
  ['FY', 'FlyFirefly'],
  ['FZ', 'flyDubai'],
  ['G0', 'Albatros Airlines'],
  ['G2', 'GullivAir'],
  ['G3', 'GOL Linhas Aereas Inteligentes'],
  ['G4', 'Allegiant Air'],
  ['G5', 'China Express Airlines'],
  ['G6', 'GlobalX Airlines'],
  ['G7', 'GoJet Airlines'],
  ['G8', 'Guyane Express Fly'],
  ['G9', 'Air Arabia'],
  ['GA', 'Garuda'],
  ['GB', 'ABX Air'],
  ['GC', 'Gelix Airlines'],
  ['GD', 'Aviair'],
  ['GE', 'Global Airways and Lift'],
  ['GF', 'Gulf Air'],
  ['GH', 'Georgian Airlines'],
  ['GI', 'China Central Longhao Airlines'],
  ['GJ', 'Getjet Airlines Latvia'],
  ['GK', 'Jetstar Japan'],
  ['GL', 'Air Greenland'],
  ['GN', 'Air Gabon'],
  ['GO', 'Air Ghana'],
  ['GP', 'APG Airlines'],
  ['GQ', 'Sky Express'],
  ['GR', 'Aurigny Air Services'],
  ['GS', 'Tianjin Airlines'],
  ['GT', 'Air Guilin'],
  ['GV', 'Grant Aviation'],
  ['GW', 'GetJet Airlines'],
  ['GX', 'Guangxi Beibu Gulf Airlines'],
  ['GY', 'Colorful GuiZhou Airlines'],
  ['GZ', 'Air Rarotonga'],
  ['H1', 'Hahn Air Systems'],
  ['H2', 'Sky Airline'],
  ['H4', 'HiSky Europe'],
  ['H5', 'CM Airlines'],
  ['H6', 'European Air Charter'],
  ['H7', 'HiSky'],
  ['H8', 'Sky Airline Peru'],
  ['H9', 'Himalaya Airlines'],
  ['HA', 'Hawaiian Airlines'],
  ['HB', 'Greater Bay Airlines'],
  ['HC', 'Air Senegal'],
  ['HD', 'Air Do'],
  ['HF', 'Air Cote d Ivoire'],
  ['HG', 'Hala Air'],
  ['HH', 'Qanot Sharq'],
  ['HK', 'Skippers Aviation'],
  ['HM', 'Air Seychelles'],
  ['HN', 'Hadhramout Airways'],
  ['HO', 'Juneyao Airlines'],
  ['HP', 'PopulAir'],
  ['HR', 'Hahn Air Lines'],
  ['HT', 'Air Horizont'],
  ['HU', 'Hainan Airlines'],
  ['HV', 'Transavia'],
  ['HW', 'North-Wright Airways'],
  ['HX', 'Hong Kong Airlines'],
  ['HY', 'Uzbekistan Airways'],
  ['HZ', 'Aurora Airlines'],
  ['I2', 'Iberia Express'],
  ['I4', 'Island Air Express'],
  ['I5', 'Air India Express'],
  ['I6', 'IRYO'],
  ['I7', 'IndiaOne Air'],
  ['I9', 'Central Airlines'],
  ['IA', 'Iraqi Airways'],
  ['IB', 'Iberia'],
  ['IC', 'Fly91'],
  ['ID', 'Batik Air'],
  ['IE', 'Solomon Airlines'],
  ['IF', 'Fly Baghdad Airline'],
  ['IG', 'GEA'],
  ['IH', 'Southern Sky'],
  ['II', 'IBC Airways'],
  ['IJ', 'Spring Japan'],
  ['IK', 'Air Kiribati'],
  ['IM', 'Jupiter Jet'],
  ['IN', 'Nam Air'],
  ['IO', 'IrAero'],
  ['IP', 'Pelita Air'],
  ['IQ', 'Qazaq Air'],
  ['IR', 'Iran Air'],
  ['IT', 'Tigerair Taiwan'],
  ['IV', 'GP Aviation'],
  ['IW', 'Wings Air'],
  ['IX', 'Air India Express'],
  ['IY', 'Yemen Airways'],
  ['IZ', 'Arkia Israeli Airlines'],
  ['J2', 'Azerbaijan Airlines'],
  ['J3', 'Northwestern Air Lease'],
  ['J4', 'Badr Airlines'],
  ['J6', 'JetSMART Airlines - Colombia'],
  ['J7', 'Afrijet'],
  ['J8', 'Berjaya Air'],
  ['J9', 'Jazeera Airways'],
  ['JA', 'JetSMART'],
  ['JB', 'British Caledonian Airways (Charter)'],
  ['JC', 'Japan Air Commuter'],
  ['JD', 'Beijing Capital Airlines'],
  ['JE', 'Jettainer'],
  ['JH', 'Fuji Dream Airlines'],
  ['JI', 'Armenian Airlines'],
  ['JJ', 'Latam Airlines Brasil'],
  ['JK', 'AerCaribe'],
  ['JL', 'Japan Airlines'],
  ['JM', 'Jambojet '],
  ['JN', 'Alaska Air Transit'],
  ['JO', 'Jasmin Airways'],
  ['JP', 'Jettime'],
  ['JQ', 'Jetstar Airways'],
  ['JR', 'Joy Air'],
  ['JS', 'Air Koryo'],
  ['JT', 'Lion Airlines'],
  ['JU', 'Air Serbia'],
  ['JV', 'Bearskin Airlines'],
  ['JW', 'Private Wings'],
  ['JX', 'STARLUX Airlines'],
  ['JY', 'InterCaribbean Airways'],
  ['JZ', 'jetSMART Peru'],
  ['K2', 'Yute Commuter Service'],
  ['K3', 'Taquan Air'],
  ['K4', 'Kalitta Air'],
  ['K5', 'Skycooler'],
  ['K6', 'Air Cambodia'],
  ['K8', 'Mercury ULD'],
  ['K9', 'TezJet'],
  ['KA', 'Aero Nomad Airlines'],
  ['KB', 'Royal Bhutan Airlines'],
  ['KC', 'Air Astana'],
  ['KE', 'Korean Air'],
  ['KF', 'Air Belgium'],
  ['KG', 'Key Lime Air'],
  ['KJ', 'Air Incheon'],
  ['KK', 'LEAV Aviation'],
  ['KL', 'KLM Royal Dutch Airlines'],
  ['KM', 'KM Malta Airlines'],
  ['KN', 'China United Airlines'],
  ['KP', 'ASKY'],
  ['KQ', 'Kenya Airways'],
  ['KR', 'Cambodia Airways'],
  ['KS', 'Air Connect'],
  ['KU', 'Kuwait Airways'],
  ['KV', 'Krasavia'],
  ['KW', 'AeroStan'],
  ['KX', 'Cayman Airways'],
  ['KY', 'Kunming Airlines'],
  ['L4', 'The Landline Company'],
  ['L5', 'Red Air'],
  ['L6', 'Mauritanian Airlines'],
  ['L8', 'Lulutai Airlines'],
  ['L9', 'Lumiwings'],
  ['LA', 'LATAM Airlines'],
  ['LB', 'Libyan Express'],
  ['LC', 'La Costeña S.A.'],
  ['LD', 'AHK Air Hong Kong'],
  ['LF', 'Contour Airlines'],
  ['LG', 'Luxair'],
  ['LH', 'Lufthansa'],
  ['LI', 'ETF Airways'],
  ['LJ', 'Jin Air'],
  ['LK', 'Lao Skyway'],
  ['LL', 'LEVEL'],
  ['LM', 'Loganair'],
  ['LN', 'Libyan Airlines'],
  ['LO', 'LOT - Polish Airlines'],
  ['LP', 'LATAM Airlines Peru'],
  ['LR', 'Avianca Costa Rica'],
  ['LS', 'Jet2'],
  ['LT', 'LongJiang Airlines'],
  ['LU', 'LATAM Airlines Chile'],
  ['LV', 'AIRZENA'],
  ['LW', 'Lauda Europe'],
  ['LX', 'Swiss'],
  ['LY', 'EL AL'],
  ['LZ', 'Legend Airlines'],
  ['M5', 'Kenmore Air'],
  ['M6', 'Amerijet International'],
  ['M8', 'Euroavia Airlines'],
  ['M9', 'Motor-Sich'],
  ['MA', 'Elitavia Malta'],
  ['MB', 'Chrono Aviation'],
  ['MD', 'Air Madagascar'],
  ['ME', 'MEA'],
  ['MF', 'Xiamen Airlines'],
  ['MG', 'Eznis Airways'],
  ['MH', 'Malaysia Airlines'],
  ['MI', 'Freebird Airlines Europe'],
  ['MJ', 'MyWay Airlines'],
  ['MK', 'Air Mauritius'],
  ['ML', 'Sky Mali'],
  ['MM', 'Peach'],
  ['MN', 'Asman Airlines'],
  ['MO', 'Calm Air International'],
  ['MQ', 'Envoy Air'],
  ['MR', 'Hunnu Air'],
  ['MS', 'Egyptair'],
  ['MT', 'Malta MedAir'],
  ['MU', 'China Eastern Airlines'],
  ['MV', 'Air Mediterranean'],
  ['MW', 'Malta Air'],
  ['MX', 'Breeze Airways'],
  ['MY', 'Maswings'],
  ['MZ', 'Amakusa Airlines'],
  ['N0', 'Norse Atlantic Airways'],
  ['N2', 'Aero'],
  ['N4', 'Nordwind Airlines'],
  ['N5', 'Nolinor Aviation'],
  ['N7', 'NORRA'],
  ['N8', 'National Airlines'],
  ['N9', 'Shree Airlines'],
  ['NA', 'Binani Air'],
  ['NB', 'Berniq Airways'],
  ['NE', 'Nesma Airlines'],
  ['NF', 'Air Vanuatu'],
  ['NG', 'NOVAIR'],
  ['NH', 'All Nippon Airways'],
  ['NI', 'Portugália Airlines'],
  ['NK', 'Spirit Airlines'],
  ['NL', 'Amelia International'],
  ['NM', 'Air Moana'],
  ['NO', 'Neos'],
  ['NP', 'Nile Air'],
  ['NQ', 'Air Japan'],
  ['NR', 'Manta Air'],
  ['NS', 'Hebei Airlines'],
  ['NT', 'Binter Canarias'],
  ['NU', 'Japan Transocean Air '],
  ['NX', 'Air Macau'],
  ['NY', 'New York Airways'],
  ['NZ', 'Air New Zealand'],
  ['O2', 'Hopscotch Air'],
  ['O3', 'SF Airlines'],
  ['O4', 'Andes Lineas Aereas'],
  ['O7', 'Omni-blu Aviation'],
  ['O8', 'Marathon Airlines'],
  ['OA', 'Olympic Air'],
  ['OB', 'Boliviana de Aviacion'],
  ['OD', 'Batik Air'],
  ['OE', 'Fly One Airlines'],
  ['OF', 'Overland Airways'],
  ['OG', 'PLAY'],
  ['OH', 'PSA Airlines'],
  ['OJ', 'Nyxair'],
  ['OL', 'Samoa Airways'],
  ['OM', 'MIAT - Mongolian Airlines'],
  ['ON', 'Nauru Airlines'],
  ['OO', 'SkyWest Airlines'],
  ['OP', 'PassionAir'],
  ['OQ', 'Chong Qing Airlines'],
  ['OR', 'TUI fly Netherlands'],
  ['OS', 'Austrian'],
  ['OT', 'Avant Airlines'],
  ['OU', 'Croatia Airlines'],
  ['OV', 'SalamAir'],
  ['OW', 'Skyward Express'],
  ['OX', 'Skyline'],
  ['OY', 'Omni Air'],
  ['OZ', 'Asiana Airlines'],
  ['P0', 'Proflight Zambia'],
  ['P2', 'AirKenya Express'],
  ['P5', 'Wingo'],
  ['P6', 'Privilege Style'],
  ['P7', 'Supernova Airlines'],
  ['P8', 'SprintAir'],
  ['P9', 'Asia Pacific Airlines'],
  ['PA', 'Airblue'],
  ['PB', 'PAL Airlines'],
  ['PC', 'Pegasus Airlines'],
  ['PD', 'Porter Airlines'],
  ['PE', "People's"],
  ['PF', 'AirSial'],
  ['PG', 'Bangkok Airways'],
  ['PH', 'Pionair'],
  ['PI', 'Polar Airlines'],
  ['PJ', 'Air Saint Pierre'],
  ['PK', 'Pakistan International Airlines'],
  ['PL', 'Benin Airlines'],
  ['PM', 'Canaryfly'],
  ['PN', 'China West Air'],
  ['PP', 'Propair.'],
  ['PQ', 'SkyUp Airlines'],
  ['PR', 'Philippine Airlines'],
  ['PS', 'Ukraine International Airlines'],
  ['PT', 'Piedmont Airlines'],
  ['PU', 'Plus Ultra'],
  ['PV', 'Saint Barth Commuter'],
  ['PW', 'Precision Air Services'],
  ['PX', 'Air Niugini'],
  ['PY', 'Surinam Airways'],
  ['PZ', 'LATAM Airlines Paraguay'],
  ['Q2', 'Maldivian'],
  ['Q3', 'Anguilla Air Services'],
  ['Q4', 'Euro Airlines'],
  ['Q5', '40-Mile Air'],
  ['Q6', 'Volaris Costa Rica'],
  ['Q9', 'Green Africa Airways'],
  ['QB', 'Qeshm Air'],
  ['QC', 'Camair-Co'],
  ['QE', 'Express Freighters Australia'],
  ['QF', 'Qantas Airways'],
  ['QH', 'Bamboo Airways'],
  ['QI', 'Ibom Airlines'],
  ['QK', 'Jazz Aviation'],
  ['QL', 'LASER Airlines'],
  ['QN', 'Skytrans Airlines'],
  ['QO', 'Quikjet Airlines'],
  ['QP', 'Akasa Air'],
  ['QQ', 'Alliance Airlines'],
  ['QR', 'Qatar Airways'],
  ['QS', 'Smartwings'],
  ['QU', 'Skyline Express Airlines'],
  ['QV', 'Lao Airlines'],
  ['QW', 'Qingdao Airlines'],
  ['QX', 'Horizon Air'],
  ['QZ', 'Indonesia AirAsia'],
  ['R1', 'Zapways'],
  ['R2', 'Transair'],
  ['R3', 'Yakutia Air'],
  ['R5', 'Jordan Aviation'],
  ['R6', 'DAT'],
  ['R8', 'Reguljair'],
  ['R9', 'Trans Executive Airlines'],
  ['RA', 'Nepal Airlines'],
  ['RB', 'Syrian Arab Airlines'],
  ['RC', 'Atlantic Airways'],
  ['RD', 'Easycharter'],
  ['RE', 'Airhub Airlines'],
  ['RF', 'Aero K '],
  ['RG', 'Rotana Jet'],
  ['RI', 'RIMBUN AIR'],
  ['RJ', 'Royal Jordanian'],
  ['RK', 'Ryanair UK'],
  ['RO', 'TAROM'],
  ['RP', 'Budapest Aircraft Service'],
  ['RQ', 'Kam Air'],
  ['RR', 'BUZZ'],
  ['RS', 'Air Seoul'],
  ['RV', 'Air Canada Rouge'],
  ['RV', 'Air Canada rouge'],
  ['RW', 'Royal Air Philippines'],
  ['RX', 'Riyadh Air'],
  ['RZ', 'Servicios Aereos Nacionales SANSA'],
  ['S0', 'Aerolineas Sosa'],
  ['S2', 'Star Marianas Air'],
  ['S3', 'SATCO'],
  ['S4', 'Azores Airlines'],
  ['S5', 'Abakan Air'],
  ['S7', 'S7 Airlines'],
  ['S8', 'Sky Capital Airlines'],
  ['S9', 'FlyBig'],
  ['SA', 'South African Airways'],
  ['SB', 'Air Calin'],
  ['SC', 'Shandong Airlines'],
  ['SD', 'Sudan Airways'],
  ['SE', 'Sky Vision Airlines'],
  ['SF', 'Tassili Airlines'],
  ['SG', 'SpiceJet'],
  ['SH', 'Sharp Airlines'],
  ['SI', 'Sierra Pacific Airlines'],
  ['SJ', 'Sriwijaya Air'],
  ['SK', 'SAS'],
  ['SL', 'SAS Connect Ireland'],
  ['SM', 'Air Cairo'],
  ['SN', 'Brussels Airlines'],
  ['SO', 'Syphax Airlines'],
  ['SP', 'SATA - Air Acores'],
  ['SQ', 'Singapore Airlines'],
  ['SR', 'Skyway Airlines'],
  ['SS', 'CorsAir'],
  ['ST', 'Air Thanlwin'],
  ['SU', 'Aeroflot'],
  ['SV', 'Saudi Arabian Airlines'],
  ['SW', 'Swiss Airtainer'],
  ['SX', 'Skywagon'],
  ['SY', 'Sun Country Airlines'],
  ['SZ', 'Somon Air'],
  ['T3', 'Eastern Airways'],
  ['T4', 'Topre Corporation'],
  ['T5', 'Turkmenistan Airlines'],
  ['T6', 'AirSWIFT'],
  ['T7', 'Twin Jet'],
  ['T9', 'Turpial Airlines'],
  ['TB', 'TUI fly Belgium'],
  ['TC', 'Air Tanzania'],
  ['TD', 'Tbilisi Airways'],
  ['TE', 'SkyTaxi'],
  ['TF', 'Braathens Regional Airways'],
  ['TG', 'Thai Airways International'],
  ['TH', 'Raya Airways'],
  ['TI', 'Tailwind Airlines'],
  ['TJ', 'Tradewind Aviation'],
  ['TK', 'Turkish Airlines'],
  ['TL', 'Airnorth'],
  ['TM', 'LAM'],
  ['TN', 'Air Tahiti Nui'],
  ['TO', 'Transavia France'],
  ['TP', 'TAP Portugal'],
  ['TQ', 'Swift Air'],
  ['TQ', 'Towards Air'],
  ['TR', 'Scoot'],
  ['TS', 'Air Transat'],
  ['TT', 'Braathens International Airways'],
  ['TU', 'Tunisair'],
  ['TV', 'Tibet Airlines'],
  ['TW', "T'Way Airline"],
  ['TX', 'Air Caraibes'],
  ['TX', 'Air Caraibes'],
  ['TY', 'Air Caledonie'],
  ['U2', 'easyJet'],
  ['U3', 'Sky Gates Airlines'],
  ['U4', 'Buddha Air'],
  ['U5', 'SkyUp MT'],
  ['U6', 'Ural Airlines'],
  ['U7', 'TashkentAir'],
  ['U8', 'Tus Airways'],
  ['UA', 'United Airlines'],
  ['UB', 'Myanmar National Airlines'],
  ['UD', 'UR Airlines'],
  ['UF', 'Petroleum Air Services'],
  ['UG', 'Tunisair Express'],
  ['UI', 'Auric Air'],
  ['UJ', 'Al Masria Universal Airlines'],
  ['UK', 'British Island Airways'],
  ['UL', 'SriLankan Airlines'],
  ['UM', 'Air Zimbabwe'],
  ['UN', 'United Nigeria Airlines'],
  ['UO', 'Hong Kong Express Airways'],
  ['UP', 'Bahamasair'],
  ['UQ', 'Urumqi Airlines'],
  ['UR', 'Uganda Airlines'],
  ['US', 'SILK AVIA'],
  ['UT', 'Utair Aviation'],
  ['UU', 'Air Austral'],
  ['UX', 'Air Europa'],
  ['UY', 'Umza Air'],
  ['UZ', 'Buraq Air'],
  ['V0', 'Conviasa'],
  ['V3', 'Carpatair'],
  ['V4', 'Vieques Air Link'],
  ['V5', 'Aerovias DAP'],
  ['V7', 'Volotea'],
  ['V9', 'Van Air Europe'],
  ['VA', 'Virgin Australia'],
  ['VB', 'VivaAerobus'],
  ['VC', 'Sterling Airways / Aleutian Airways'],
  ['VE', 'Clic'],
  ['VF', 'AJet'],
  ['VG', 'Fly Vaayu'],
  ['VI', 'Volga-Dnepr'],
  ['VJ', 'VietJet Air'],
  ['VK', 'ValueJet'],
  ['VL', 'Lufthansa City'],
  ['VM', 'Max Air'],
  ['VN', 'Vietnam Airlines'],
  ['VO', 'Universal Air'],
  ['VP', 'Villa Air'],
  ['VQ', 'Novoair'],
  ['VR', 'TACV Cabo Verde Airlines'],
  ['VS', 'Virgin Atlantic'],
  ['VT', 'Air Tahiti'],
  ['VU', 'Vietravel Airlines'],
  ['VV', 'Pattaya Airways'],
  ['VY', 'Vueling Airlines'],
  ['VZ', 'Thai Vietjet Air'],
  ['W2', 'Flexflight'],
  ['W3', 'Arik Air'],
  ['W4', 'Wizz Air Malta '],
  ['W5', 'Mahan Air'],
  ['W6', 'Wizz Air'],
  ['W7', 'Makers Air'],
  ['W9', 'Wizz Air UK'],
  ['WA', 'KLM Cityhopper'],
  ['WB', 'RwandAir'],
  ['WC', 'Meregrass'],
  ['WE', 'THAI Smile Airways'],
  ['WF', 'Widerøe'],
  ['WG', 'Sunwing Airlines'],
  ['WH', 'Wingo'],
  ['WI', 'White Airways'],
  ['WJ', 'JetSmart Airlines'],
  ['WK', 'Edelweiss Air'],
  ['WN', 'Southwest Airlines'],
  ['WO', 'National Jet Express'],
  ['WP', 'Wasaya Airways'],
  ['WR', 'Westjet Encore'],
  ['WS', 'Westjet'],
  ['WT', 'Swiftair'],
  ['WV', 'FlyNamibia'],
  ['WW', 'MJets Air'],
  ['WX', 'Cityjet'],
  ['WY', 'Oman Air'],
  ['WZ', 'Red Wings Airlines'],
  ['X3', 'TUIFly'],
  ['X7', 'Challenge Airlines'],
  ['X9', 'Avion Express'],
  ['XC', 'Corendon Airlines'],
  ['XE', 'JSX Air'],
  ['XG', 'USC'],
  ['XJ', 'Thai AirAsia X'],
  ['XK', 'Air Corsica'],
  ['XL', 'Latam Airlines Ecuador'],
  ['XM', 'Zimex Aviation'],
  ['XN', 'Manasik Aviation'],
  ['XO', 'SEAir'],
  ['XP', 'Avelo Airlines'],
  ['XQ', 'SunExpress'],
  ['XR', 'Corendon Airlines Europe'],
  ['XV', 'Ivoire Airways'],
  ['XY', 'Flynas'],
  ['Y0', 'Yellow Air Taxi'],
  ['Y2', 'Air Century'],
  ['Y4', 'Volaris'],
  ['Y5', 'Hayways'],
  ['Y7', 'NordStar'],
  ['Y8', 'Suparna Airlines'],
  ['Y9', 'Kish Air'],
  ['YB', 'Harbour Air Seaplanes'],
  ['YD', 'Ascend Airways'],
  ['YE', 'Yanair'],
  ['YH', 'Sunsplash Aviation'],
  ['YI', 'FLY OYA'],
  ['YK', 'Avia Traffic Company'],
  ['YL', 'Libyan Wings'],
  ['YM', 'Montenegro Airlines'],
  ['YP', 'Air Premia'],
  ['YQ', 'TAR México'],
  ['YR', 'Scenic Airlines'],
  ['YS', 'Flightlink'],
  ['YT', 'Yeti Airlines'],
  ['YU', 'EuroAtlantic Airways'],
  ['YV', 'Mesa Airlines'],
  ['YW', 'Air Nostrum'],
  ['YX', 'Republic Airline'],
  ['Z0', 'Norse Atlantic UK'],
  ['Z2', 'AirAsia Philippines'],
  ['Z4', 'Fly Red Sea'],
  ['Z7', 'CAMEX Airlines'],
  ['Z9', 'Aero Zambia'],
  ['ZA', 'Sky Angkor Airlines'],
  ['ZB', 'Air Albania'],
  ['ZD', 'EWA Air'],
  ['ZE', 'Eastar Jet'],
  ['ZG', 'ZIPAIR'],
  ['ZH', 'Shenzhen Airlines'],
  ['ZI', 'Aigle Azur'],
  ['ZK', 'Zetavia'],
  ['ZL', 'Rex Airlines'],
  ['ZN', 'Zambia Airways'],
  ['ZP', 'Paranair'],
  ['ZS', 'Aviation Horizons'],
  ['ZT', 'Titan Airways'],
  ['ZU', 'Azman Air'],
  ['ZW', 'Air Wisconsin'],
  ['ZY', 'Eznis Airways'],
  ['4Y', 'Discover Airlines'],
  ['8Z', 'Congo Airways'],
] as const;

export type AirlineCode = (typeof airlines)[number][0];

export const airlinesMap = new Map<string, string>(
  airlines.map(([code, name]) => [code, name]),
);
